### PR TITLE
Encode everything to ASCII

### PR DESCRIPTION
**Pull request by gear4s**
and discard characters that cannot be printed

Fixed "UnicodeEncodeError: 'ascii' codec can't encode character u'\U0001f60a' in position 54: ordinal not in range(128)"

### CODE REVIEW

**Comment by fish-face** [comment]
This is not the correct fix for this issue. Python automatically encodes unicode strings to whatever it believes is the encoding the terminal expects to receive. On the computer I'm currently using, `print(u"\U0001f60a")' works fine, and this change would actually break such a message on my computer, because it wouldn't be printed when it should be!

There are two things going on: firstly, I suspect your environment's locale is set up wrong or strangely, or you're on windows, so that python thinks (perhaps incorrectly) that it is expecting ASCII. You can probably fix this in your terminal or shell settings, unless you're in Windows which I don't know much about. What you're looking for is that the sys.stdout.encoding variable in a python shell has a sensible value (UTF-8, probably, but maybe something else. Not ASCII though.) The second thing is that when this does occur, the failure is not handled gracefully.

Now I am not sure how to handle it properly. We could catch the UnicodeEncodeError and re-encode to UTF-8 (which will print everything but result in garbage characters) or ASCII/sys.stdout.encoding and ignore unencodable characters (which will drop some characters silently without warning the user that they're missing some stuff).

**Comment by gear4s** [comment]
I'm on archlinux, and my terminal allows utf-8 by default. happens on ubuntu too

**Comment by fish-face** [comment]
If you launch a python shell and execute

    import sys
    sys.stdout.encoding

What does it say?
What about

    echo $LC_CTYPE

from a terminal?

**Comment by gear4s** [comment]
yo, sorry for the long wait. I completely forgot about this.

```
bash4.4.12 load: 1.13 Fri Mar 24 22:25:38
[ dev/dev-PC ; ~/git ]> echo $LC_CTYPE


bash4.4.12 load: 1.13 Fri Mar 24 22:27:17
[ dev/dev-PC ; ~/git ]> python
Python 3.6.0 (default, Jan 16 2017, 12:12:55) 
[GCC 6.3.1 20170109] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.stdout.encoding
'UTF-8'
>>> 

bash4.4.12 load: 1.13 Fri Mar 24 22:27:26
[ dev/dev-PC ; ~/git ]> python2
Python 2.7.13 (default, Dec 21 2016, 07:16:46) 
[GCC 6.2.1 20160830] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.stdout.encoding
'UTF-8'
>>>
```

**Comment by fish-face** [comment]
OK that's pretty strange. Could you try printing a non-ASCII character in the python terminal? e.g. print(u"\U0001f60a") / print u"\U0001f60a"?

And assuming that works without an exception, could you, on the line before your change, also add a print statement:
    print sys.stdout.encoding
Then run quasselgrep - preferably whatever command you ran before which elicited the exception - and put the result here, to see if the environment is somehow being set weirdly only when quasselgrep is run.

While we're on that subject, how are you running quasselgrep? Is it just  in an ordinary terminal locally, via ssh, or using the client/server feature?

**Comment by fish-face** [comment]
Not sure what's going on here but I think it's invalid.

**Pull request closed without merging**
